version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgre_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend


  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: web
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - web
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - backend


networks:
  backend:

volumes:
  postgre_data:
  prometheus_data: